parameters:
  kernel.secret: yoursecretshouldbehere
  app_path: "../.."

framework:
  form: false
  assets: false
  session: false
  translator: false
  php_errors:
    log: false

dbal:
  connections:
    users:
      driver: sqlite
      host:
      port:
      user: root
      password: root
      dbname: ':memory:'

# config/services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\DBAL\:
    resource: '%app_path%/src/DBAL/*'

  App\Domain\Model\User\InMemoryUserRepository:
  App\Domain\Model\User\UserRepository:
    alias: App\Domain\Model\User\InMemoryUserRepository

  #
  # Controllers
  #
  App\Controller\:
    resource: "%app_path%/src/Controller/*"
    tags:
      - { name: controller.service_arguments }

  App\Domain\QueryHandler\:
    resource: "%app_path%/src/Domain/QueryHandler"
    tags: [ 'query_handler' ]
